# Generated by Django 5.0.6 on 2024-06-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_student_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('roll_number', models.CharField(default=None, max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default=None, max_length=100)),
                ('department', models.CharField(default=None, max_length=100)),
                ('subject', models.CharField(default=None, max_length=100)),
                ('remarks', models.CharField(default=None, max_length=100)),
                ('application_document', models.CharField(default=None, max_length=100)),
                ('state', models.IntegerField(choices=[(0, 'inward'), (1, 'outward')], default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
