const listdata = [
    {
        "id": 1,
        "roll_number": "23B1234",
        "date": "01/05/2024",
        "name": "Arjun Mehta",
        "department": "Computer Science",
        "subject": "Application for Leave",
        "remarks": "Approved",
        "application_document": "application",
        "state": "inward"
    },
    {
        "id": 2,
        "roll_number": "23B5678",
        "date": "02/05/2024",
        "name": "Priya Sharma",
        "department": "Electrical Engineering",
        "subject": "Request for Transcript",
        "remarks": "",
        "application_document": "document",
        "state": "outward"
    },
    {
        "id": 3,
        "roll_number": "23B9101",
        "date": "03/05/2024",
        "name": "Vikram Patel",
        "department": "Mechanical Engineering",
        "subject": "Change of Major",
        "remarks": "Pending",
        "application_document": "application",
        "state": "inward"
    },
    {
        "id": 4,
        "roll_number": "23B2345",
        "date": "04/05/2024",
        "name": "Neha Singh",
        "department": "Civil Engineering",
        "subject": "Application for Internship",
        "remarks": "Rejected",
        "application_document": "document",
        "state": "outward"
    },
    {
        "id": 5,
        "roll_number": "23B6789",
        "date": "05/05/2024",
        "name": "Ravi Verma",
        "department": "Chemical Engineering",
        "subject": "Request for Recommendation",
        "remarks": "",
        "application_document": "application",
        "state": "inward"
    },
    {
        "id": 6,
        "roll_number": "23B1122",
        "date": "06/05/2024",
        "name": "Anjali Nair",
        "department": "Aerospace Engineering",
        "subject": "Application for Scholarship",
        "remarks": "Approved",
        "application_document": "document",
        "state": "outward"
    },
    {
        "id": 7,
        "roll_number": "23B3344",
        "date": "07/05/2024",
        "name": "Manish Gupta",
        "department": "Biotechnology",
        "subject": "Request for Course Withdrawal",
        "remarks": "Pending",
        "application_document": "application",
        "state": "inward"
    },
    {
        "id": 8,
        "roll_number": "23B5566",
        "date": "08/05/2024",
        "name": "Sneha Reddy",
        "department": "Environmental Engineering",
        "subject": "Application for Re-evaluation",
        "remarks": "Rejected",
        "application_document": "document",
        "state": "outward"
    },
    {
        "id": 9,
        "roll_number": "23B7788",
        "date": "09/05/2024",
        "name": "Amit Kulkarni",
        "department": "Industrial Engineering",
        "subject": "Request for Certificate",
        "remarks": "",
        "application_document": "application",
        "state": "inward"
    },
    {
        "id": 10,
        "roll_number": "23B9900",
        "date": "10/05/2024",
        "name": "Lakshmi Iyer",
        "department": "Materials Engineering",
        "subject": "Application for Study Abroad",
        "remarks": "Approved",
        "application_document": "document",
        "state": "outward"
    },
    {
        "id": 11,
        "roll_number": "23B2233",
        "date": "11/05/2024",
        "name": "Karan Joshi",
        "department": "Nuclear Engineering",
        "subject": "Request for Extension",
        "remarks": "Pending",
        "application_document": "application",
        "state": "inward"
    },
    {
        "id": 12,
        "roll_number": "23B4455",
        "date": "12/05/2024",
        "name": "Deepika Rao",
        "department": "Petroleum Engineering",
        "subject": "Application for Workshop",
        "remarks": "Approved",
        "application_document": "document",
        "state": "outward"
    },
    {
        "id": 13,
        "roll_number": "23B6677",
        "date": "13/05/2024",
        "name": "Vivek Desai",
        "department": "Robotics Engineering",
        "subject": "Request for Leave",
        "remarks": "",
        "application_document": "application",
        "state": "inward"
    },
    {
        "id": 14,
        "roll_number": "23B8899",
        "date": "14/05/2024",
        "name": "Pooja Kapoor",
        "department": "Software Engineering",
        "subject": "Application for Project",
        "remarks": "Pending",
        "application_document": "document",
        "state": "outward"
    },
    {
        "id": 15,
        "roll_number": "23B1010",
        "date": "15/05/2024",
        "name": "Rohit Bansal",
        "department": "Telecommunications Engineering",
        "subject": "Request for Sponsorship",
        "remarks": "Rejected",
        "application_document": "application",
        "state": "inward"
    },
    {
        "id": 16,
        "roll_number": "23B2121",
        "date": "16/05/2024",
        "name": "Anita Shah",
        "department": "Automobile Engineering",
        "subject": "Application for Competition",
        "remarks": "Approved",
        "application_document": "document",
        "state": "outward"
    },
    {
        "id": 17,
        "roll_number": "23B3232",
        "date": "17/05/2024",
        "name": "Sanjay Agarwal",
        "department": "Biomedical Engineering",
        "subject": "Request for Seminar",
        "remarks": "",
        "application_document": "application",
        "state": "inward"
    },
    {
        "id": 18,
        "roll_number": "23B4343",
        "date": "18/05/2024",
        "name": "Aishwarya Menon",
        "department": "Construction Engineering",
        "subject": "Application for Research Grant",
        "remarks": "Pending",
        "application_document": "document",
        "state": "outward"
    },
    {
        "id": 19,
        "roll_number": "23B5454",
        "date": "19/05/2024",
        "name": "Suresh Gupta",
        "department": "Energy Engineering",
        "subject": "Request for Reschedule",
        "remarks": "Rejected",
        "application_document": "application",
        "state": "inward"
    },
    {
        "id": 20,
        "roll_number": "23B6565",
        "date": "20/05/2024",
        "name": "Nidhi Chatterjee",
        "department": "Mining Engineering",
        "subject": "Application for Transfer",
        "remarks": "Approved",
        "application_document": "document",
        "state": "outward"
    },
    {
        "id": 21,
        "roll_number": "23B7676",
        "date": "21/05/2024",
        "name": "Tarun Pillai",
        "department": "Textile Engineering",
        "subject": "Request for Deferral",
        "remarks": "Pending",
        "application_document": "application",
        "state": "inward"
    },
    {
        "id": 22,
        "roll_number": "23B8787",
        "date": "22/05/2024",
        "name": "Rekha Sinha",
        "department": "Metallurgical Engineering",
        "subject": "Application for Training",
        "remarks": "Rejected",
        "application_document": "document",
        "state": "outward"
    },
    {
        "id": 23,
        "roll_number": "23B9898",
        "date": "23/05/2024",
        "name": "Gaurav Reddy",
        "department": "Geological Engineering",
        "subject": "Request for Equipment",
        "remarks": "",
        "application_document": "application",
        "state": "inward"
    },
    {
        "id": 24,
        "roll_number": "23B1011",
        "date": "24/05/2024",
        "name": "Meera Khan",
        "department": "Naval Architecture",
        "subject": "Application for Fellowship",
        "remarks": "Approved",
        "application_document": "document",
        "state": "outward"
    },
    {
        "id": 25,
        "roll_number": "23B2322",
        "date": "25/05/2024",
        "name": "Nitin Sharma",
        "department": "Architectural Engineering",
        "subject": "Request for Extension",
        "remarks": "Pending",
        "application_document": "application",
        "state": "inward"
    },
    {
        "id": 26,
        "roll_number": "23B3434",
        "date": "26/05/2024",
        "name": "Preeti Singh",
        "department": "Industrial Design",
        "subject": "Application for Competition",
        "remarks": "Approved",
        "application_document": "document",
        "state": "outward"
    },
    {
        "id": 27,
        "roll_number": "23B4545",
        "date": "27/05/2024",
        "name": "Rajesh Nair",
        "department": "Automobile Engineering",
        "subject": "Request for Sponsorship",
        "remarks": "Pending",
        "application_document": "application",
        "state": "inward"
    },
    {
        "id": 28,
        "roll_number": "23B5656",
        "date": "28/05/2024",
        "name": "Shilpa Roy",
        "department": "Civil Engineering",
        "subject": "Application for Re-evaluation",
        "remarks": "Rejected",
        "application_document": "document",
        "state": "outward"
    },
    {
        "id": 29,
        "roll_number": "23B6767",
        "date": "29/05/2024",
        "name": "Mohan Desai",
        "department": "Biotechnology",
        "subject": "Request for Equipment",
        "remarks": "",
        "application_document": "application",
        "state": "inward"
    },
    {
        "id": 30,
        "roll_number": "23B7878",
        "date": "30/05/2024",
        "name": "Kiran Patel",
        "department": "Environmental Engineering",
        "subject": "Request for Transcript",
        "remarks": "",
        "application_document": "document",
        "state": "outward"
    },
    {
        "id": 31,
        "roll_number": "23B8989",
        "date": "31/05/2024",
        "name": "Suman Mishra",
        "department": "Mechanical Engineering",
        "subject": "Application for Re-evaluation",
        "remarks": "Pending",
        "application_document": "application",
        "state": "inward"
    },
    {
        "id": 32,
        "roll_number": "23B9090",
        "date": "01/06/2024",
        "name": "Aditya Saxena",
        "department": "Electrical Engineering",
        "subject": "Request for Recommendation",
        "remarks": "Approved",
        "application_document": "document",
        "state": "outward"
    },
    {
        "id": 33,
        "roll_number": "23B1212",
        "date": "02/06/2024",
        "name": "Leena Pandey",
        "department": "Chemical Engineering",
        "subject": "Application for Research",
        "remarks": "",
        "application_document": "application",
        "state": "inward"
    },
    {
        "id": 34,
        "roll_number": "23B2323",
        "date": "03/06/2024",
        "name": "Akhil Chawla",
        "department": "Computer Science",
        "subject": "Request for Deferral",
        "remarks": "Pending",
        "application_document": "document",
        "state": "outward"
    },
    {
        "id": 35,
        "roll_number": "23B3434",
        "date": "04/06/2024",
        "name": "Isha Das",
        "department": "Civil Engineering",
        "subject": "Application for Internship",
        "remarks": "Rejected",
        "application_document": "application",
        "state": "inward"
    },
    {
        "id": 36,
        "roll_number": "23B4545",
        "date": "05/06/2024",
        "name": "Rahul Verma",
        "department": "Biotechnology",
        "subject": "Request for Course Withdrawal",
        "remarks": "",
        "application_document": "document",
        "state": "outward"
    },
    {
        "id": 37,
        "roll_number": "23B5656",
        "date": "06/06/2024",
        "name": "Megha Rathi",
        "department": "Aerospace Engineering",
        "subject": "Application for Workshop",
        "remarks": "Approved",
        "application_document": "application",
        "state": "inward"
    },
    {
        "id": 38,
        "roll_number": "23B6767",
        "date": "07/06/2024",
        "name": "Arvind Bhatt",
        "department": "Nuclear Engineering",
        "subject": "Request for Equipment",
        "remarks": "Pending",
        "application_document": "document",
        "state": "outward"
    },
    {
        "id": 39,
        "roll_number": "23B7878",
        "date": "08/06/2024",
        "name": "Ritika Sharma",
        "department": "Materials Engineering",
        "subject": "Application for Leave",
        "remarks": "",
        "application_document": "application",
        "state": "inward"
    },
    {
        "id": 40,
        "roll_number": "23B8989",
        "date": "09/06/2024",
        "name": "Varun Malhotra",
        "department": "Metallurgical Engineering",
        "subject": "Request for Sponsorship",
        "remarks": "Approved",
        "application_document": "document",
        "state": "outward"
    }
];

export default listdata;
